### ISSUE TITLE
Cannot start a live streaming on Android 12 and Android 11

### ISSUE THREAD

**Issue by carolpettirossi** [apivideo/api.video-reactnative-live-stream#13]
Hello everyone, 

I'm trying to use this library with Cloudflare Stream and I can't make it work properly on Android latest versions. 

It seems to work fine on Android 9. 

This is the code:

```
<LivestreamView
  style={{
    height: 300,
    backgroundColor: "black",
    alignSelf: "stretch",
  }}
  ref={cameraViewRef}
  video={{
    fps: 30,
    resolution: "720p",
    camera: "front",
    orientation: "portrait",
  }}
  rtmpServerUrl="rtmps://live.cloudflare.com:443/live/"
  liveStreamKey={
    "32d69c287f287a426405a0840b581043k341b948cd3334c5f8c1c74e97794adc6"
  }
  onConnectionSuccess={() => {
    console.log("success");
    setStreaming(true);

    //do what you want
  }}
  onConnectionFailed={(e) => {
    console.log("fail", e);
    setStreaming(false);
    setStreamKey(null);
    //do what you want
  }}
  onDisconnect={() => {
    console.log("disconnect");
    setStreaming(false);
    setStreamKey(null);

    //do what you want
  }}
/>

<Button
  onPress={() => {
    if (streaming) {
      console.log('streaming');
      cameraViewRef.current?.stopStreaming();
      false;
    } else {
      console.log('else');
      cameraViewRef.current?.startStreaming();
    }
  }}
  title={streaming ? "stop" : "start 2"}
  color="red"
/>
```

I can't see any logs on metro.

If I debug the APK this is the error I get:

```
2022-01-19 22:04:11.443 28188-28188/? E/unknown:UIViewOperationQueue: Unhandled SoftException
    java.io.IOException: Could not start RTMP streaming. audioReady=false, videoReady=true
        at video.api.livestream_module.ApiVideoLiveStream.startStreaming(ApiVideoLiveStream.kt:179)
        at com.apivideoreactnativelivestream.ReactNativeLivestreamViewManager.startStreaming(ReactNativeLivestreamViewManager.kt:177)
        at com.apivideoreactnativelivestream.ReactNativeLivestreamViewManager.receiveCommand(ReactNativeLivestreamViewManager.kt:88)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:839)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.executeWithExceptions(UIViewOperationQueue.java:317)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:873)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1079)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:775)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
``` 

Any ideas on what I'm missing or how can I fix it?

Thank you :)

**Comment by ThibaultBee** [comment]
Hi Carol,

I guess there is something wrong with the default audio configuration.
Have you noticed other logcat traces above this exception?

**Comment by Drakezair** [comment]
> Hi Carol,
> 
> I guess there is something wrong with the default audio configuration. Have you noticed other logcat traces above this exception?

H im working with carol, How should the audio be configured?

this is the only log we have, because the apk doesnt fail only is not conecting to rmtp, and throws that log.

thanks @ThibaultBee

**Comment by carolpettirossi** [comment]
Hi @ThibaultBee, 

Thanks for the quick reply. In addition to the above, we also have the config below in our `AndroidManifest.xml`

```
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.FLASHLIGHT"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by carolpettirossi** [comment]
Hi @ThibaultBee, 

I guess we are not asking for correct permissions. What I've done so far is:

- Added <uses-feature android:name="android.hardware.microphone" /> to the AndroidManifest.xml
- Added permissions manually using App info on android phone 

I can get the streaming started properly on Cloudflare. However, it doesn't seem to be sending the image properly. The streaming starts but when I check Cloudflare there's no image. 
Any ideas?

**Comment by ThibaultBee** [comment]
Hi,

Glad to hear that you fix your problem.
The permission to record audio with the microphone is:

```
<uses-permission android:name="android.permission.RECORD_AUDIO" />
```

I am not sure what is this permission: `<uses-feature android:name="android.hardware.microphone" />`
I guess you hadn't accepted the permission in the app.

Have you tried to send the RTMP stream to a ffplay instance? Like this:

```
ffplay -listen 1 -i rtmp://0.0.0.0:1935/s/yourStreamKey
```

On your smartphone, set the RTMP URL to your computer IP address `rtmp://0.0.0.0:1935/s/`.

**Comment by 39otrebla** [comment]
Same issue here on Mi 10 T with Android 11. I see the following errors in logcat right after the `OpenGLViewBase` thread started:

```
.... E/libc: Access denied finding property "persist.vendor.camera.privapp.list"
.... E/FMQ: grantorIdx must be less than 3
- 
```

**Comment by ThibaultBee** [comment]
Hi Alberto,
As far as I know when codec starts in an Android device, there is always error.
Could you open another issue with a precise description and a complete logcat please?

Regards,
Thibault

**Comment by 39otrebla** [comment]
@ThibaultBee I found the issue... on Android, if you use a custom `rtmpUrl`, it should end with `/`, otherwise the connection fails. It works fine out-of-the-box on iOS. Not sure if this is intentional or not, I'll open an issue.

**Comment by ThibaultBee** [comment]
Yes, this is related to https://github.com/apivideo/api.video-reactnative-live-stream/issues/8
Should be fix soon.
