### ISSUE TITLE
[Bug]: LifecycleScope is not available

### ISSUE THREAD

**Issue by ThibaultBee** [apivideo/api.video-reactnative-live-stream#91]
### Version

v2.0.1

### Which operating systems have you used?

- [X] Android
- [ ] iOS

### Environment that reproduces the issue

* Not relevant

### Is it reproducible in the example application?

Yes

### RTMP Server

All

### Reproduction steps

No clear, waiting for more feedback and/or an example to reproduce it.

### Expected result

No exception

### Actual result

An exception is thrown:
 E  FATAL EXCEPTION: pool-40-thread-1
 Process: com.**********, PID: 2574
 java.lang.IllegalStateException: LifecycleScope is not available
at io.github.thibaultbee.streampack.views.PreviewView.startPreviewIfReady(PreviewView.kt:272)
at io.github.thibaultbee.streampack.views.PreviewView.startPreview(PreviewView.kt:245)
at video.api.livestream.views.ApiVideoView.startPreview$livestream_release(ApiVideoView.kt:62)
at video.api.livestream.ApiVideoLiveStream$startPreview$1.invoke(ApiVideoLiveStream.kt:373)
at video.api.livestream.ApiVideoLiveStream$startPreview$1.invoke(ApiVideoLiveStream.kt:364)
at video.api.reactnative.livestream.LiveStreamView$1$1.invoke(LiveStreamView.kt:75)
at video.api.reactnative.livestream.LiveStreamView$1$1.invoke(LiveStreamView.kt:72)
at video.api.reactnative.livestream.utils.permissions.SerialPermissionsManager$requestPermissions$request$1$1.invoke(SerialPermissionsManager.kt:38)
at video.api.reactnative.livestream.utils.permissions.SerialPermissionsManager$requestPermissions$request$1$1.invoke(SerialPermissionsManager.kt:35)
at video.api.reactnative.livestream.utils.permissions.PermissionsManager$requestPermissions$1.onAllGranted(PermissionsManager.kt:51)
at video.api.reactnative.livestream.utils.permissions.PermissionsManager.requestPermissions(PermissionsManager.kt:76)
at video.api.reactnative.livestream.utils.permissions.PermissionsManager.requestPermissions(PermissionsManager.kt:49)
at video.api.reactnative.livestream.utils.permissions.SerialPermissionsManager.requestPermissions$lambda$1(SerialPermissionsManager.kt:35)
at video.api.reactnative.livestream.utils.permissions.SerialPermissionsManager.$r8$lambda$dzig6asy22NzT_1QrKBawhgieas(Unknown Source:0)
at video.api.reactnative.livestream.utils.permissions.SerialPermissionsManager$$ExternalSyntheticLambda1.run(Unknown Source:10)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)

### Additional context

See:
https://github.com/apivideo/api.video-reactnative-live-stream/issues/81#issuecomment-2230992214
https://github.com/apivideo/api.video-reactnative-live-stream/issues/81#issuecomment-2328834599
Workaround: https://github.com/apivideo/api.video-reactnative-live-stream/issues/81#issuecomment-2331200824

**Comment by talhatsk** [comment]
hi @ThibaultBee i have upgrade to 2.0.1 version and facing this crash, is there any way to overcome this crash programmatically?

**Comment by ThibaultBee** [comment]
I don't have any workaround. Have you tried this workaround https://github.com/apivideo/api.video-reactnative-live-stream/issues/81#issuecomment-2331200824?

Could provide a way to reproduce this crash? (a fork of the exampl, a code snippet,...)

**Comment by adaerodriguez** [comment]
I have the same issue. Any news?

**Comment by ThibaultBee** [comment]
Can anyone test on the `main` branch?

```
yarn add git@github.com:apivideo/api.video-reactnative-live-stream.git
```

**Comment by dev-asfand** [comment]
I have the same issue. Any news?
Please

**Comment by NeuDam** [comment]
Has anyone got a solution?

**Comment by ThibaultBee** [comment]
> Can anyone test on the `main` branch?
> 
> ```
> yarn add git@github.com:apivideo/api.video-reactnative-live-stream.git
> ```

There is a solution. Could someone test it?

**Comment by talhatsk** [comment]
> > Can anyone test on the `main` branch?
> > ```
> > yarn add git@github.com:apivideo/api.video-reactnative-live-stream.git
> > ```
> 
> There is a solution. Could someone test it?

i'll check the main branch

**Comment by talhatsk** [comment]
@ThibaultBee main branch works fine

**Comment by ThibaultBee** [comment]
So, is this issue solved on the `main` branch?

**Comment by talhatsk** [comment]
> So, is this issue solved on the `main` branch?

yes seems like this issue is not in main branch

**Comment by talhatsk** [comment]
is there any expected release for this fix? @ThibaultBee

**Comment by dev-asfand** [comment]
Hi. I have got the solution 

if you are installing the latest version of the package 2.0.1 on below React native version 0.76.0 ... then you will get LifeCycle error. 

I have upgraded ma RN version to 0.76.0 and its resolved

**Comment by talhatsk** [comment]
> Hi. I have got the solution
> 
> if you are installing the latest version of the package 2.0.1 on below React native version 0.76.0 ... then you will get LifeCycle error.
> 
> I have upgraded ma RN version to 0.76.0 and its resolved

i have checked by upgrading but it didn't work? is there any extra step?

**Comment by maurovisintin** [comment]
Same, I' upgraded to 0.76.6 but still got the same 'LifecycleScope' error

**Comment by maurovisintin** [comment]
I manually applied the changes on this commit
https://github.com/apivideo/api.video-reactnative-live-stream/commit/00fceab1e34fe8145bbb50fe160913e12de5b923
and it worked
